### PR TITLE
corrected banner and footer and removed extra white spaces

### PR DESCRIPTION
**Pull request by selmakishwar**

### CODE REVIEW

**Comment by gvwilson** [comment]
Thanks for the pull request, but as far as I can see, it just deletes 
the banner PNG - there are no changes to the CSS.  Am I missing something?

https://github.com/gvwilson/feeling-responsive/pull/16

Thanks,
Greg

**Comment by selmakishwar** [comment]
My sincerest apologies.  There was an error while committing and all the
changes were not included. We will correct this problem today . Once again,
sorry for the inconvenience.
Thank you,
Selma Kishwar
Phaseit, Inc

**Comment by gvwilson** [comment]
Hi Selma,
No worries - I just wanted to make sure I was looking at the right branch.
Cheers,
Greg

**Comment by gvwilson** [comment]
When I build and serve this locally using `make serve` (which runs `jekyll serve --config _config.yml,_config_dev.yml`), and look at the footer of the home page, I see this:

screen shot 2015-11-08 at 9 03 31 pm

The social media icons appear to be missing, and so is the "top of page" icon. What do you see when you build and serve on your machine?

**Comment by selmakishwar** [comment]
I have noticed this problem early on with the original webpage. Sometimes
the icons are viewable and other times they disappear. The same problem
occurs with my clone. I will be more than happy to take a look and resolve
this for you.

**Comment by gvwilson** [comment]
Sites that use the Feeling Responsive template without modifications 
(e.g. http://www.datacarpentry.org/) don't seem to have problems - no 
idea what's causing it.

**Comment by selmakishwar** [comment]
No worries. I will find the problem.

**Comment by selmakishwar** [comment]
good afternoon.
i am trying to resolve the matter of the disappearing icons.  here is a
problem that i have noticed.
http://gvwilson.github.io/feeling-responsive/
and
http://dev.software-carpentry.org

have different results.  the first has the disappearing icons and the
latter has the icons in place.  could this be from two different
repositories? if so, would it be possible for  me to  see the source
of http://dev.software-carpentry.org so that i may view the
differences  to resolve this matter quickly?

thank you,

Selma Kishwar

Phaseit, Inc

ᐧ

**Comment by gvwilson** [comment]
Hi Selma; thanks for your mail.  I haven't updated 
http://dev.software-carpentry.org since October 16; I believe it's based 
on revision 7310626223bb from 
git@github.com:gvwilson/feeling-responsive.git.

Cheers,
Greg

On 2015-11-10 10:44 PM, Phaseit, Inc wrote:
> good afternoon.
> i am trying to resolve the matter of the disappearing icons. here is a
> problem that i have noticed.
> http://gvwilson.github.io/feeling-responsive/
> and
> http://dev.software-carpentry.org
>
> have different results. the first has the disappearing icons and the
> latter has the icons in place. could this be from two different
> repositories? if so, would it be possible for me to see the source
> of http://dev.software-carpentry.org so that i may view the
> differences to resolve this matter quickly?
>
> thank you,
>
> Selma Kishwar
>
> Phaseit, Inc
>
> ᐧ
>
> On Sun, Nov 8, 2015 at 3:20 PM, selma kishwar <selmaikishwar@gmail.com>
> wrote:
>
> > No worries. I will find the problem.
> > On Nov 8, 2015 3:19 PM, "Greg Wilson" <notifications@github.com> wrote:
> >
> >> Sites that use the Feeling Responsive template without modifications
> >> (e.g. http://www.datacarpentry.org/) don't seem to have problems - no
> >> idea what's causing it.
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/gvwilson/feeling-responsive/pull/16#issuecomment-154874937>
> >> .
> >>
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/gvwilson/feeling-responsive/pull/16#issuecomment-155591781>.
>

-- 
Email longa, vita brevis.

**Comment by selmakishwar** [comment]
good afternoon.
after researching the disappearing icons i have come to the following
conclusion.
as its structured now the icons can only be viewed when served by github.
the following is the error message that i have been receiving:

Font from origin 'http://dev.software-carpentry.org' has been blocked from
loading by Cross-Origin Resource Sharing policy: No
'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://gvwilson.github.io' is therefore not allowed access.

would you like a structure that can be portable between github and software
carpentry? because right now the cross site restriction means the icons
have to be served the same as the site itself.

thank you,
selma kishwar
Phaseit, Inc
ᐧ

**Comment by gvwilson** [comment]
Where is the cross-origin policy set?  Is it a server setting in 
dev.software-carpentry.org?  If so, we can change that.

**Comment by selmakishwar** [comment]
it is important that you receive an accurate response to this question.
 please allow me a little time so that i may give you a correct response. i
will have an answer for you soon.
thanks,
selma
ᐧ

**Comment by gvwilson** [comment]
Merging this one since it seems to be a step in the right direction.

**Pull request merged**
